### ISSUE TITLE
Suspense, loop of XHR requests and suggested code structure

### ISSUE THREAD

**Issue by SweVictor** [crimx/observable-hooks#9]
Hi,
First, great project, thanks!

Second: I quickly ran into the issue more clearly stated in the `use-suspense` project, I think adding a similar note here would be very helpful.

> **Beware**
> Due to the design of Suspense, each time a suspender is thrown, the children of Suspense Component will be destroyed and reloaded. Do not initialize async data and trigger Suspense in the same Component.

So: related to the above design choice of Suspense, do you have a recommendation of how to structure the code? Let's say I have `MyComponent` containing logic and `MyComponentUI` containing only the interface parts. The api contains a method returning a $apiStream which generates an XHR when subscribed to.

Would the suggested design be to place the `new ObservableResource($apiStream)` in `MyComponent` and then pass that as a prop to `MyComponentUI` where `useObservableSuspense(observableResource)` is called? 

Would you recommend "caching" the `observableResource` between different resources as an in-memory solution? If so, when would the XHR be generated?

Lastly: I actually found this project looking for a less hacky solution to trigger an `ErrorBoundary` in async events (observables typically) than `this.setState(() {throw new Error("will be caught by ErrorBoundary")})`. Any thoughts since `observable-hooks` swallows errors currently if I understood the other discussions correctly.

Thanks again for a great project!
/Victor

**Comment by crimx** [comment]
Hi,

> Would the suggested design be to place the new ObservableResource($apiStream) in MyComponent and then pass that as a prop to MyComponentUI where useObservableSuspense(observableResource) is called?

This is absolutely fine. But you'll have to `useMemo` or `useRef` to hold the observableResource in MyComponent so that it won't be repeatedly created.

The main difference between ObservableResource and Promise based resource is that observables can emit multiple times. Other than that they are very similar. You can basically just adopt any other patterns and leave out the "reload" part.

A recommended one is [Render-as-You-Fetch](https://observable-hooks.js.org/guide/render-as-you-fetch-suspense.html) which is a pattern suggested in the React docs.

> Would you recommend "caching" the observableResource between different resources as an in-memory solution? If so, when would the XHR be generated?

What do you mean by '"caching" the observableResource between different resources'? If you need to comsume values from a resource it must not be destroyed.

> If so, when would the XHR be generated?

Depending on you own logic. It can be triggered via event callbacks or based on other observables... See the [example](https://observable-hooks.js.org/examples/suspense.html).

 > Any thoughts since observable-hooks swallows errors currently if I understood the other discussions correctly.

Errors from the observable will be rethrown by ObservableResource in a Error-boundary-catchable way. [Docs](https://observable-hooks.js.org/guide/render-as-you-fetch-suspense.html#error-handling).

**Comment by SweVictor** [comment]
Ok, great, thanks for those replies and suggestions. Good point about the need to use useMemo().

Regarding emitted errors they don't seem to reach the error boundary in my project (unless using the useObservableSuspense method or manually forcing the error to the react "stack" using for example a hook hack like below). The "render as you fetch" example is really cool by the way!

```
export const useAsyncThrower = () => {
    const [_, setState] = useState();

    return (error: any) =>
        setState(() => {
            throw error;
        });
};
```

Feel free to close this issue, thanks again for the input.

**Comment by crimx** [comment]
> Regarding emitted errors they don't seem to reach the error boundary in my project (unless using the useObservableSuspense method or manually forcing the error to the react "stack" using for example a hook hack like below).

Note that I said the error is rethrown by `ObservableResource`. This happens in render phase that is why errors could reach the error boundary. This design is meant to align to the default Promise based Suspense behavior.

Error boundary does not work with async callbacks. If you want to let error boundary handle async errors, try to catch and let the observable `next` errors instead of `error` the errors.

```js
function CompA() {
  const [data, onClick] = useObservableState(
    event$ => event$.pipe(
      switchMap(() => from(fetchData()).pipe(
        map(response => response.data),
        catchError(e => of(e))
      ))
    )
  )

  if (data instanceof Error) {
    throw data
    // or you can throw a new error with current stack
  }
}
```

You can easily make a custom hook out of this pattern.

Note that due to the design of RxJS, an observable is dead as soon as an error occurs. A good practice is to prevent errors reaching any observable or `catchError` in inner observables.
